package hib;
// Generated Dec 2, 2018 6:50:28 PM by Hibernate Tools 4.3.5.Final

/**
 * History generated by hbm2java
 */
public class History implements java.io.Serializable {

	private HistoryId id;
	private Users users;
	private Mediaitems mediaitems;

	public History() {
	}

	public History(HistoryId id, Users users, Mediaitems mediaitems) {
		this.id = id;
		this.users = users;
		this.mediaitems = mediaitems;
	}

	public HistoryId getId() {
		return this.id;
	}

	public void setId(HistoryId id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Mediaitems getMediaitems() {
		return this.mediaitems;
	}

	public void setMediaitems(Mediaitems mediaitems) {
		this.mediaitems = mediaitems;
	}

}
